version: "3"

services:

  wordpress:
    build:
      context: volumes/wordpress
      args:
        - XDEBUG=$XDEBUG
    container_name: "${COMPOSE_PROJECT_NAME}_wordpress"
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./volumes/uploads/:/app/wp-content/uploads
      - ./volumes/wordpress/wp-content/themes/cook-theme/:/app/wp-content/themes/cook-theme/
    env_file: .env

  db:
    image: mysql:5.7
    container_name: "${COMPOSE_PROJECT_NAME}_db"
    ports:
      - 3306:3306
    volumes:
      - ./volumes/sql/:/docker-entrypoint-initdb.d/
    env_file: .env
