import '../globals.css'
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <body className="bg-slate-800">
        <header>
          <Link href="/" className="font-extrabold"><span>L</span></Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
